down:
  path:
    image: d://img

zhihu:
  url:
    include: data[*].is_normal,admin_closed_comment,reward_info,is_collapsed,annotation_action,annotation_detail,collapse_reason,is_sticky,collapsed_by,suggest_edit,comment_count,can_comment,content,editable_content,voteup_count,reshipment_settings,comment_permission,created_time,updated_time,review_info,relevant_info,question,excerpt,relationship.is_authorized,is_author,voting,is_thanked,is_nothelp;data[*].mark_infos[*].url;data[*].author.follower_count,badge[?(type=best_answerer)].topics
    sort_by: default
    maxLimit: 20

oppo:
  threadNum: 3
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.jdbc.Driver

    ##validate  加载hibernate时，验证创建数据库表结构
    ##create   每次加载hibernate，重新创建数据库表结构，这就是导致数据库表数据丢失的原因。
    ##create-drop        加载hibernate时创建，退出是删除表结构
    ##update                 加载hibernate自动更新数据库结构
    ##validate 启动时验证表的结
    ##none  启动时不做任何操作
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
